package com.peopleapps.dto.guarantee;

import java.time.LocalDateTime;
import java.util.UUID;

public class AdmGuaranteeListDto {

    public final Long guarantee_id;
    public final Long credit_id;
    public final Long no_year;
    public final Long no_reference;
    public final String name_farm;
    public final String owner;
    public final Long address_id;
    public final String address_line;
    public final String no_public;
    public final Long no_farm;
    public final Long no_folder;
    public final Long document_account_id;
    public final Long address_state_id;
    public final String address_state_desc;
    public final Long address_city_id;
    public final String address_city_desc;
    public final Long address_account_id;
    public final Long document_type_id;
    public final String document_type_desc;
    public final Long testimony;
    public final Double rope_value;
    public final Double area_meters;
    public final Double msnm;
    public final String topography;
    public final String hydrography;
    public final String soil_quality;
    public final String plan_cover;
    public final String cultivate_detail;
    public final String farm_neighbor;
    public final String risk_class_form;
    public final String irrigation_extension;
    public final String building_detail;
    public final String annotation;
    public final String north_origin;
    public final String south_origin;
    public final String orient_origin;
    public final String west_origin;
    public final String communication_routes;
    public final Long state;
    public final Long city;
    public final String to_city;
    public final Long evaluator;
    public final String evaluator_name;
    public final String evaluator_email;
    public final UUID evaluator_key;
    public final LocalDateTime date_created;
    public final Long created_by;
    public final String created_email;
    public final UUID created_key;
    public final Long status_id;
    public final String status_desc;
    public final String no_book;
    public final String ownership_rights;
    public final Double no_rope;
    public final Double no_hectares;
    public final Double cost_per_square_meter;
    public final Double height_above_sea_level;
    public final Double value_of_permanent_crops;
    public final Double value_of_buildings;
    public final String annotation_2;

    public AdmGuaranteeListDto(Long guarantee_id, Long credit_id, Long no_year, Long no_reference, String name_farm, String owner, Long address_id, String address_line, String no_public, Long no_farm, Long no_folder, Long document_account_id, Long address_state_id, String address_state_desc, Long address_city_id, String address_city_desc, Long address_account_id, Long document_type_id, String document_type_desc, Long testimony, Double rope_value, Double area_meters, Double msnm, String topography, String hydrography, String soil_quality, String plan_cover, String cultivate_detail, String farm_neighbor, String risk_class_form, String irrigation_extension, String building_detail, String annotation, String north_origin, String south_origin, String orient_origin, String west_origin, String communication_routes, Long state, Long city, String to_city, Long evaluator, String evaluator_name, String evaluator_email, UUID evaluator_key, LocalDateTime date_created, Long created_by, String created_email, UUID created_key, Long status_id, String status_desc, String no_book, String ownership_rights, Double no_rope, Double no_hectares, Double cost_per_square_meter, Double height_above_sea_level, Double value_of_permanent_crops, Double value_of_buildings, String annotation_2) {
        this.guarantee_id = guarantee_id;
        this.credit_id = credit_id;
        this.no_year = no_year;
        this.no_reference = no_reference;
        this.name_farm = name_farm;
        this.owner = owner;
        this.address_id = address_id;
        this.address_line = address_line;
        this.no_public = no_public;
        this.no_farm = no_farm;
        this.no_folder = no_folder;
        this.document_account_id = document_account_id;
        this.address_state_id = address_state_id;
        this.address_state_desc = address_state_desc;
        this.address_city_id = address_city_id;
        this.address_city_desc = address_city_desc;
        this.address_account_id = address_account_id;
        this.document_type_id = document_type_id;
        this.document_type_desc = document_type_desc;
        this.testimony = testimony;
        this.rope_value = rope_value;
        this.area_meters = area_meters;
        this.msnm = msnm;
        this.topography = topography;
        this.hydrography = hydrography;
        this.soil_quality = soil_quality;
        this.plan_cover = plan_cover;
        this.cultivate_detail = cultivate_detail;
        this.farm_neighbor = farm_neighbor;
        this.risk_class_form = risk_class_form;
        this.irrigation_extension = irrigation_extension;
        this.building_detail = building_detail;
        this.annotation = annotation;
        this.north_origin = north_origin;
        this.south_origin = south_origin;
        this.orient_origin = orient_origin;
        this.west_origin = west_origin;
        this.communication_routes = communication_routes;
        this.state = state;
        this.city = city;
        this.to_city = to_city;
        this.evaluator = evaluator;
        this.evaluator_name = evaluator_name;
        this.evaluator_email = evaluator_email;
        this.evaluator_key = evaluator_key;
        this.date_created = date_created;
        this.created_by = created_by;
        this.created_email = created_email;
        this.created_key = created_key;
        this.status_id = status_id;
        this.status_desc = status_desc;
        this.no_book = no_book;
        this.ownership_rights = ownership_rights;
        this.no_rope = no_rope;
        this.no_hectares = no_hectares;
        this.cost_per_square_meter = cost_per_square_meter;
        this.height_above_sea_level = height_above_sea_level;
        this.value_of_permanent_crops = value_of_permanent_crops;
        this.value_of_buildings = value_of_buildings;
        this.annotation_2 = annotation_2;
    }
}
